### PR TITLE
Properly merge headers when one of the sides is a mock matcher

### LINKED ISSUE #316: mockClient .with({ headers: m.anything() }) not mocking if 2 different instances of forge(...) is used
# Expected Behavior

When having multiple instances of same `forge` helper function the `mockClient(instance)...when({ headers: m.anything() })` should mock the request.

# Current Behavior

When having multiple instances of same `forge` helper function, then `mockClient(instance)...when({ headers: m.anything() })` is not mocking the request only throwing an error with partial match.

# Previous Behavior 

This worked before in version `2.32.1` when headers was not checked, could be an issue in `isExactMatch` [src/mocks/mock-request.js]

## Failure Logs

  `[Error: [Mappersmith Test] No exact match found for "GET localhost/users" (body: "undefined"; headers: "x-special-header=value"), partial match with "GET localhost/users" (body: "function () return true; }"; headers: "random-header=value"), check your mock definition],`

## Steps to Reproduce

```
import forge from 'mappersmith'
import { mockClient, install, uninstall, m } from 'mappersmith/test'

const createApi = (headers = {}) =>
  forge({
    ignoreGlobalMiddleware: true,
    allowResourceHostOverride: true,
    gatewayConfigs: {
      enableHTTP408OnTimeouts: true,
    },
    middleware: [],
    host: 'localhost',
    resources: {
      User: {
        all: { path: '/users', headers },
      },
    },
  })

describe('mockClient', () => {
  beforeEach(install)
  afterEach(uninstall)

  it('should be able to use function in .with on headers to mock request with 2 different instances', async () => {
    const api = createApi()
    const user = { firstName: 'foo', lastName: 'bar' }
    mockClient(createApi({ 'random-header': 'value' }))
      .resource('User')
      .method('all')
      .with({ body: m.anything(), headers: m.anything() })
      .response([user])
      .assertObject()

    const data = await api.User.all({ headers: { 'X-Special-Header': 'value' } })
    const users = data.data()

    expect(users[0]).toEqual(user)
  })

  it('works if using same headers', async () => {
    const api = createApi()
    const user = { firstName: 'foo', lastName: 'bar' }
    const headers = { 'random-header': 'value' }
    mockClient(createApi(headers))
      .resource('User')
      .method('all')
      .with({ body: m.anything(), headers: m.anything() })
      .response([user])
      .assertObject()

    const data = await api.User.all({ headers })
    const users = data.data()

    expect(users[0]).toEqual(user)
  })

  it('works if using same instance in mockClient', async () => {
    const api = createApi()
    const user = { firstName: 'foo', lastName: 'bar' }
    const headers = { 'random-header': 'value' }
    mockClient(api)
      .resource('User')
      .method('all')
      .with({ body: m.anything(), headers: m.anything() })
      .response([user])
      .assertObject()

    const data = await api.User.all({ headers })
    const users = data.data()

    expect(users[0]).toEqual(user)
  })
})
```

### PR DESCRIPTION
**Pull request by Yurickh**
Closes #316

### CODE REVIEW

File: src/request.ts [hunk 1]
```diff
@@ -185,6 +185,11 @@ export class Request {
   public headers() {
     const headerAttr = this.methodDescriptor.headersAttr
     const headers = (this.requestParams[headerAttr] || {}) as Headers
```
Comment (Yurickh) [inline src/request.ts:187]: It's rather sad that the types here are lying, since we know this can be a function, as evidenced by the line after this.
The problem is that having functions for headers is a thing that's highly specific to mocks, and changing the type here will affect everything that calls `request.headers()` to have to treat possible function returns.

Comment (Yurickh) [reply src/request.ts:187]: IMHO this is one more case for not creating a Request between MockResource and MockRequest, but this afaict is a breaking change :T

**Review by Nevon — APPROVED** [review]

**Review by klippx — APPROVED** [review]
