### PR TITLE
Fix: memory leak with when using Http(s)Agent keepAlive=true

### LINKED ISSUE #390: Bug: memory leak with when using Http(s)Agent keepAlive=true
When using `HttpAgent` with `{keepAlive: true}`, the request socket never gets destroyed which is not taken into account by the code that registers event observers against said socket object. 

This means that this block of code:

https://github.com/tulios/mappersmith/blob/1fdaacc/src/gateway/http.ts#L94-L114

... will evaluate on every request and will - in reality - target same socket object instance.

The result is a valid/concerning node runtime warning that some object is getting overloaded by event observers. 

## Proof

Using modified version of the fist example given in the README as proof:

```typescript
import forge from 'mappersmith';
import {Agent as HttpsAgent} from 'https';

const httpAgent = new HttpsAgent({keepAlive: true});
const github = forge({
  clientId: 'example',
  host: 'https://example.com/',
  gatewayConfigs: {
    HTTP: {configure: () => ({agent: httpAgent})},
  },
  resources: {
    Status: {
      beepBoop: {path: '/'},
    },
  },
});

(async () => {
  for (let i = 0; i < 50; i += 1) {
    github.Status.beepBoop().then(() => {
      process.stdout.write('.');
    });
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
})();
```

### Expected output

```txt
..................................................
```

### Actual output

```txt
.............................(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 lookup listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 secureConnect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
.....(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 lookup listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 secureConnect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
................
```

## Proposed fix

One can just make sure not to re-register the observers when socket is reused which can be easily detected via request object property:

```typescript
if (!httpRequest.reusedSocket) {
  httpRequest.on('socket', (socket) => {
    // ... redacted
  })
}
```

### PR DESCRIPTION
**Pull request by notanengineercom**
Fixes #390 
This pull request contains:
- [The spec](https://github.com/tulios/mappersmith/pull/391/files#diff-f7285d0cc47d59dcea7a2d0488dbdee625f914ff697b5bd9b574b8e160758545R91-R98) to reproduce the memory leak condition and the fix
- Inverted logic for the [sockets related event listener assignments](https://github.com/tulios/mappersmith/pull/391/files#diff-97d4b84b631227c34c616f2edd0036181c063f4d022e56009ecba4b3e171f8c2R104-R106). The event listeners only register if the specific hook is defined in the HTTP gatewayConfig object.

The spec fails without the fix: when keep-alive is enabled, the tcp socket events register twice (once per API call):
> [test] 1) integration HTTP event callbacks keep alive
[test]   Message:
[test]     Expected 2 to be 1.
[test]   Stack:
[test]         at <Jasmine>
[test]         at Object.verifySockets (/Users/notanengineer/Documents/GitHub/mappersmith/spec/integration/node/support/keep-alive.js:13:46)
[test]         at /Users/notanengineer/Documents/GitHub/mappersmith/spec/integration/node/integration.spec.js:95:27
[test]         at processTicksAndRejections (node:internal/process/task_queues:96:5)
[test]   Message:
[test]     Expected 2 to be 1.
[test]   Stack:
[test]         at <Jasmine>
[test]         at Object.verifySockets (/Users/notanengineer/Documents/GitHub/mappersmith/spec/integration/node/support/keep-alive.js:14:47)
[test]         at /Users/notanengineer/Documents/GitHub/mappersmith/spec/integration/node/integration.spec.js:95:27
[test]         at processTicksAndRejections (node:internal/process/task_queues:96:5)
[test] 
[test] 20 specs, 1 failure
[test] Finished in 0.819 seconds

### CODE REVIEW

**Comment by allanpaiste** [comment]
@klippx @tulios perhaps you could find time to confirm the validity of this PR and get this merged/released? :)

File: src/gateway/http.ts [hunk 1]
```diff
@@ -96,21 +97,13 @@ export class HTTP extends Gateway {
...
-        }
-      })
-      socket.on('secureConnect', () => {
-        if (httpOptions.onSocketSecureConnect) {
-          httpOptions.onSocketSecureConnect(requestParams)
-        }
-      })
+      if (httpRequest.reusedSocket) {
+        return
+      }
```
Comment (klippx) [inline src/gateway/http.ts:102]: I am not sure I like how this is exiting prematurely and looking outside of its scope. We are attaching a listener on `performRequest` just to bail out based on something we already know on the outside, isn't it?

I would suggest to move this check to before attaching the on socket, does that make sense? (The tests are passing with this suggestion)

```ts
    if (!httpRequest.reusedSocket) {
      httpRequest.on('socket', (socket) => {
        if (httpOptions.onRequestSocketAssigned) {
          httpOptions.onRequestSocketAssigned(requestParams)
        }
        // ...
```

File: src/gateway/http.ts [hunk 2]
```diff
@@ -96,21 +97,13 @@ export class HTTP extends Gateway {
...
+
+      this.assignSocketListener(socket, 'lookup', httpOptions.onSocketLookup?.bind(null, requestParams))
+      this.assignSocketListener(socket, 'connect', httpOptions.onSocketConnect?.bind(null, requestParams))
+      this.assignSocketListener(socket, 'secureConnect', httpOptions.onSocketSecureConnect?.bind(null, requestParams))
```
Comment (klippx) [inline src/gateway/http.ts:106]: Not sure I like the indirection of having a utility function here. I can see the appeal for making these one-liners, but the rest of the code base doesn't really resonate well with it.
- we do not use `.bind(null`, which purpose is to set `this` to not be the this of the caller but to be "stateless". But then why even put it as a class function (its not even private)
- the `bind` is also a bit tricky since it is returning a new function, I would prefer to avoid it, it's too clever for me :)

I think it is much more clear / in line with the rest of the code base if we do this:

```suggestion
      if (httpOptions.onSocketLookup) {
        socket.on('lookup', () => {
          httpOptions.onSocketLookup?.(requestParams)
        })
      }
      if (httpOptions.onSocketConnect) {
        socket.on('connect', () => {
          httpOptions.onSocketConnect?.(requestParams)
        })
      }
      if (httpOptions.onSocketSecureConnect) {
        socket.on('secureConnect', () => {
          httpOptions.onSocketSecureConnect?.(requestParams)
        })
      }
```

Even if it is more "verbose" I think it is more clear what is going on, WDYT?

File: spec/integration/node/support/keep-alive.js [hunk 3]
```diff
@@ -0,0 +1,21 @@
+import createManifest from 'spec/integration/support/manifest'
+
+import forge, { configs } from 'src/index'
```
Comment (klippx) [inline spec/integration/node/support/keep-alive.js]: test locally that `yarn test` runs 

```suggestion
import forge from 'src/index'
```

File: spec/integration/node/integration.spec.js [hunk 4]
```diff
@@ -73,6 +78,24 @@ describe('integration', () => {
           done()
         })
       })
+
+      it('no keep alive', (done) => {
```
Comment (klippx) [inline spec/integration/node/integration.spec.js:82]: To me this sounds like a "describe" block since it is describing more of the _context_ when it should state what it is _testing_.

Suggestion (pseudo code):
```ts
describe("without keep alive", () => {
  beforeEach(() => {
        const httpAgent = new HttpAgent({ keepAlive: false })
        configs.gatewayConfigs.HTTP.configure = () => ({ agent: httpAgent })
  })
  it("does not reuse the socket but only attaches listeners once to http agent `sockets`", () => ...
```

(please reword appropriately since I am not 100% sure what is tested)

File: spec/integration/node/integration.spec.js [hunk 5]
```diff
@@ -73,6 +78,24 @@ describe('integration', () => {
...
+        const httpAgent = new HttpAgent({ keepAlive: false })
+        configs.gatewayConfigs.HTTP.configure = () => ({ agent: httpAgent })
+        keepAliveHelper.callApiTwice().then(() => {
+          keepAliveHelper.verifySockets(httpAgent.sockets)
+          done()
+        })
+      })
+
+      it('keep alive', (done) => {
```
Comment (klippx) [inline spec/integration/node/integration.spec.js:91]: similarly

```ts
describe("with keep alive", () => {
  beforeEach(() => {
        const httpAgent = new HttpAgent({ keepAlive: false })
        configs.gatewayConfigs.HTTP.configure = () => ({ agent: httpAgent })
  })
  it("calling the API twice reuses the socket, and only attaches listeners once to freeSockets (?)", () => ...
```

File: spec/integration/node/integration.spec.js [hunk 6]
```diff
@@ -73,6 +78,24 @@ describe('integration', () => {
...
         })
       })
+
+      it('no keep alive', (done) => {
+        const httpAgent = new HttpAgent({ keepAlive: false })
+        configs.gatewayConfigs.HTTP.configure = () => ({ agent: httpAgent })
+        keepAliveHelper.callApiTwice().then(() => {
+          keepAliveHelper.verifySockets(httpAgent.sockets)
+          done()
+        })
```
Comment (klippx) [inline spec/integration/node/integration.spec.js:88]: We can add this to both tests

```suggestion
        }).catch((response) => {
          done.fail(`test failed with promise error: ${errorMessage(response)}`)
        })
```

File: spec/integration/node/support/keep-alive.js [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+  return {
+    verifySockets: (socketsReference) => {
+      const socketOrigins = Object.keys(socketsReference)
+      expect(socketOrigins.length).toBe(1)
+      const sockets = socketsReference[socketOrigins[0]]
+      expect(sockets.length).toBe(1)
+      const socket = sockets[0]
+      expect(socket.listenerCount('lookup')).toBe(1)
+      expect(socket.listenerCount('connect')).toBe(1)
+    },
```
Comment (klippx) [inline spec/integration/node/support/keep-alive.js:15]:
```suggestion
    verifySockets: (count, socketsReference) => {
      const socketOrigins = Object.keys(socketsReference)
      if (count === 0) {
        expect(socketOrigins.length).toBe(0)
        return
      }
      expect(socketOrigins.length).toBe(1)
      const sockets = socketsReference[socketOrigins[0]]
      expect(sockets.length).toBe(1)
      const socket = sockets[0]
      expect(socket.listenerCount('lookup')).toBe(count)
      expect(socket.listenerCount('connect')).toBe(count)
    },
```


Can we add an argument to the helper to state how many `listenerCount` we are expecting?

Then we can in both tests show that we expect 0 on the one and 1 on the other which makes it a little bit better and perhaps more helpful?

```ts
        keepAliveHelper.callApiTwice().then(() => {
          keepAliveHelper.verifySockets(1, httpAgent.freeSockets)
          keepAliveHelper.verifySockets(0, httpAgent.sockets)
          done()
```

**Review by klippx — CHANGES_REQUESTED** [review]
Thanks for the PR, really great, I appreciate the effort! I hope you don't mind that I have some humble comments from my perspective, please give me your feedback and we can agree what makes sense and what does not. 🙏

File: src/gateway/http.ts (hunk 1 above)
Comment (notanengineercom) [reply src/gateway/http.ts:102]: My assumption was that `reusedSocket` property was set when the socket was assigned to the request, but I see that assumption was wrong (TIL).
My main reasoning of adding the early return inside of the **onSocket listener** was to be able to trigger the `onRequestSocketAssigned` callback. We would be skipping it on reused sockets, even though the request is new

File: src/gateway/http.ts (hunk 2 above)
Comment (notanengineercom) [reply src/gateway/http.ts:106]: Sounds good to me, I agree that the bind approach is a bit too much 😄

**Comment by klippx** [comment]
> One thing I learnt: to not rush code after work 🙈

Don't worry, I appreciate that you got a PR up including test case and all, that's more than most people will put up! 

Pending tasks
- [ ] Add test for the `onRequestSocketAssigned` callback

**Comment by notanengineercom** [comment]
> Pending tasks
> 
> - [ ] Add test for the `onRequestSocketAssigned` callback

I didn't mention it in a comment, but yesterday I pushed a commit with the test for the `onRequestSocketAssigned` callback 😄

**Review by klippx — APPROVED** [review]
