### PR TITLE
Clone mock responses

### LINKED ISSUE #158: MockClient responses should be clones
I just got bitten by a tricky test failure where the code under test was mutating the response from mappersmith, which actually caused the fixture I passed to my mock to be mutated.

Example:

```javascript
const fixture = ['item']

const mock = () => mockClient(apiClient).resource('Foo').method('list').response(fixture)

const functionUnderTest = async () => {
  const response = await apiClient.Foo.list().then(response => response.data())
  return response.shift()
}

const testFunction = async () => {
  mock()
  const items = await functionUnderTest()
  expect(items).toHaveLength(1)
}

test('first test', testFunction) // this will pass
test('second test', testFunction) // this will fail
```

This is because the Mappersmith mock returns a direct reference to the same object, rather than a copy of it.

### PR DESCRIPTION
**Pull request by klippx**
Fixes #158

### CODE REVIEW

**Comment by Nevon** [comment]
Nice! Seems like a good improvement.

File: src/utils/clone.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
+import { isPlainObject } from './index'
+
+export const clone = <T>(obj: T): T => {
+  if (isPlainObject(obj)) {
```
Comment (Yurickh) [inline src/utils/clone.ts:4]: Does this check imply that object that are instances of classes don't work with this utility? Does this behave as expected when provided an instance of Response? How about objects that have properties that are instances of, say, Request?

File: spec/browser/test/mock-resource.spec.js [hunk 2]
```diff
@@ -211,6 +211,17 @@ describe('Test lib / mock resources', () => {
...
 
+  it('returns a clone of the mocked response', async () => {
+    const response = ['foo', 'bar']
+    mockClient(client).resource('User').method('all').response(response)
+
+    const userOnFirstCall = await client.User.all().then((response) => response.data().shift())
+    const userOnSecondCall = await client.User.all().then((response) => response.data().shift())
+
+    expect(userOnSecondCall).toEqual(userOnFirstCall)
+    expect(response).toBe(response)
```
Comment (Yurickh) [inline spec/browser/test/mock-resource.spec.js:222]: I know what you wanted to check in this line, but this is impossible to fail. An object will always be itself, even if it has mutated since its creation.

File: src/utils/clone.ts (hunk 1 above)
Comment (Yurickh) [reply src/utils/clone.ts:4]: It's probably working fine right now since we only clone headers and bodies which are always plain objects, but we might want to at least leave a comment so the next person doesn't fall on the trap of cloning a whole Response.

File: src/utils/clone.spec.ts [hunk 3]
```diff
@@ -0,0 +1,77 @@
+import { clone } from './clone'
+
+describe('utils', () => {
+  describe('#clone', () => {
+    describe('for number', () => {
+      it('returns the original entry', () => {
+        // eslint-disable-next-line @typescript-eslint/no-explicit-any
+        const original = 1 as any
```
Comment (Yurickh) [inline src/utils/clone.spec.ts:8]: I'm curious why you need this `any` here. Won't `clone` accept `number` as a valid type for its T?

**Review by Yurickh — APPROVED** [review]
Nice PR :)~

File: spec/browser/test/mock-resource.spec.js (hunk 2 above)
Comment (klippx) [reply spec/browser/test/mock-resource.spec.js]: Fixed by changing this to `expect(response).toEqual(['foo', 'bar'])`

File: src/utils/clone.spec.ts (hunk 3 above)
Comment (klippx) [reply src/utils/clone.spec.ts:8]: Right, this can be removed now 👍

File: src/utils/clone.ts (hunk 1 above)
Comment (klippx) [reply src/utils/clone.ts]: Added case for instance of class
