### PR TITLE
Fix path creation with object-ish params regression

### LINKED ISSUE #281: Different query string behaviour introduced in 2.36.0
Hi,

I'm experiencing an issue in 2.36.0 and later versions of mappersmith.

When passing an array as parameters they are not being sent as they were before.

2.36.0+ behaviour:
```js
// client with path of "something"
await client.fakeResource.fakeEndpoint({
  ids: ["a", "b"]
});

// request is made to /something with no query parameter
```

Previous (2.35.0) behaviour:
```js
// client with path of "something"
await client.fakeResource.fakeEndpoint({
  ids: ["a", "b"]
});

// request is made to /something?ids[]=a&ids[]=b
```

I've reproduced this here: https://codesandbox.io/s/magical-mclaren-2usjm?file=/src/App.js 
1. Open the url on the in page browser in a new tab
2. Inspect the network requests
3. Refresh and see that the call to `/something` has no query parameters added
4. Change the mappersmith dependency to version 2.35.0 on codesandbox
5. Refresh the page you opened previously and see the call to `/something` has the query parameters added

Is this intended?

Thanks!

### PR DESCRIPTION
**Pull request by Yurickh**
Closes #281

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -44,20 +44,32 @@ export const buildRecursive = (
     return `${encodeURIComponent(key + suffix)}=${encodeURIComponent(value)}`
   }
 
-  return validKeys(value)
-    .map((k) => buildRecursive(key, value[k], suffix + '[' + k + ']'))
+  return Object.keys(value)
+    .map((nestedKey) => {
+      const nestedValue = value[nestedKey]
+      if (isNeitherNullNorUndefined(nestedValue)) {
+        return buildRecursive(key, nestedValue, suffix + '[' + nestedKey + ']')
```
Comment (Yurickh) [inline src/utils.ts:51]: I expanded the validKeys implementation here instead of making its type more magical. I needed the guarantee that `nestedValue` here is not nullish, and `validKeys` types as it is won't give me it.

File: src/types.ts [hunk 2]
```diff
@@ -16,14 +16,24 @@ export interface Params {
...
+
 export interface RequestParams {
   readonly auth?: Auth
   readonly body?: object | string
   readonly headers?: Headers
   readonly host?: string
   readonly params?: Params
   readonly timeout?: number
-  [param: string]: object | Primitive | undefined | null
+  [param: string]: object | Primitive | undefined | null | NestedParam | NestedParamArray
```
Comment (Yurickh) [inline src/types.ts:36]: Even though, in theory, all `object` type necessities should be covered by `NestedParam` here, we need it explicit here, otherwise `body`'s type becomes incompatible

**Comment by klippx** [comment]
Excellent work 🍾

**Review by klippx — APPROVED** [review]
